name: "Continuous Integration and Testing"

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.4

      - name: Install Dependencies
        run: bun install

      - name: Build Assets
        run: bun run build

      - name: Run NextJs Lint
        run: bun run next lint

      - name: Run Test
        run: bun test